name: Test Companion App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: UltraStar Play Companion

jobs:
  test-job:
    name: Test for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 6000.1.3f1
        targetPlatform:
          - Android
          - iOS
    steps:
      # Clone repo and restore cache
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}-${{ hashFiles(env.PROJECT_PATH) }}
          restore-keys: |
            Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}-
            Library-${{ env.PROJECT_PATH }}-
            Library-
      
      # Run setup script
      - name: Restore Dependencies
        run: bash build.sh RestoreCompanionAppDependencies
      
      # Test Unity project
      - name: Test Unity Project
        uses: game-ci/unity-test-runner@v4
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: all
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: "-nographics"

      # Upload test results for download
      - name: Upload Test Results
        uses: actions/upload-artifact@v4    
        if: always()
        with:
          name: Test results ${{ matrix.targetPlatform }}
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      # Publish test results for GitHub UI
      - name: Publish Test Results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: ${{ steps.testRunner.outputs.artifactsPath }}/*.xml
